Repository evolvewithevan/gitcord, pull requests merged in 2025-07, with the labels that each got.

#21 feat(uv): use uv with setuptools instead of pip with setuptools
  .gitignore
  .python-version
  BOT_SETUP.md
  pyproject.toml
  requirements-dev.txt
  requirements.txt
  setup.py
  src/gitcord/__init__.py
  src/gitcord/__main__.py
  src/gitcord/bot.py
  src/gitcord/cogs/__init__.py
  src/gitcord/cogs/general.py
  src/gitcord/config.py
  src/gitcord/events.py
  src/gitcord/utils/__init__.py
  src/gitcord/utils/helpers.py
  src/gitcord/utils/logger.py
  uv.lock
Labels: enhancement

#24 Resolve #19: manual command sync
  README.md
  README_MODULAR.md
  src/gitcord/bot.py
  src/gitcord/cogs/general.py
  src/gitcord/events.py
Labels: codex

#25 merge in-testing into main
  README.md
  README_MODULAR.md
  src/gitcord/bot.py
  src/gitcord/cogs/general.py
  src/gitcord/events.py
Labels: bug
